const mineduc = "https://especial.mineduc.cl/educacion-estudiantes-con-discapacidad-auditiva/mis-primeras-senas/";
export const EDUCATIONAL_SOURCES = [
  { id: "mineduc-diccionario", title: "Diccionario Bilingüe LSCh–Español", author: "UMCE · Ministerio de Educación", url: "https://especial.mineduc.cl/recursos-apoyo-al-aprendizaje/recursos-las-los-docentes/diccionario-bilingue-lengua-senas-chilena-espanol/", sourceUrl: "https://especial.mineduc.cl/recursos-apoyo-al-aprendizaje/recursos-las-los-docentes/diccionario-bilingue-lengua-senas-chilena-espanol/", statusNote: "Referencia para revisar significado y forma. Las fotografías no sustituyen videos de movimiento ni autorizan por sí solas el entrenamiento." },
  { id: "uv-reconocimiento", title: "Estudio: reconocimiento aislado de LSCh", author: "Miguel Yánez y Ana Aguilera · Universidad de Valparaíso", url: "https://www.scielo.cl/scielo.php?lng=en&pid=S0718-33052024000100230&script=sci_arttext", sourceUrl: "https://www.scielo.cl/scielo.php?lng=en&pid=S0718-33052024000100230&script=sci_arttext", statusNote: "Estudio con 272 clips de 17 señas y 16 participantes. Referencia metodológica; acceso a los datos y autorización de reutilización pendientes de verificar." },
  { id: "mineduc-familia", title: "Vocabulario LSCh: La Familia", author: "Centro de Innovación — Mineduc", url: "https://www.youtube.com/watch?v=J-3jA42TdMw", category: "familia", sourceUrl: "https://www.youtube.com/watch?v=J-3jA42TdMw" },
  { id: "mineduc-preguntas", title: "Vocabulario LSCh: Las Preguntas", author: "Centro de Innovación — Mineduc", url: "https://www.youtube.com/watch?v=Zvmc_ErIVNw", category: "preguntas", sourceUrl: "https://www.youtube.com/watch?v=Zvmc_ErIVNw" },
  { id: "mps-familia", title: "Mi familia — Mis Primeras Señas, capítulo 18", author: "Lóbulo Temporal · difundido por Mineduc", url: "https://www.youtube.com/watch?v=obnuRV7FS5I", category: "familia", sourceUrl: mineduc },
  { id: "mps-alimentos", title: "Alimentación saludable — Mis Primeras Señas, capítulo 16", author: "Lóbulo Temporal · difundido por Mineduc", url: "https://www.youtube.com/watch?v=iS0qXIV7Ug8", category: "alimentos", sourceUrl: mineduc },
  { id: "mps-emociones", title: "Mis emociones — Mis Primeras Señas, capítulo 14", author: "Lóbulo Temporal · difundido por Mineduc", url: "https://www.youtube.com/watch?v=RxpYvEn4eBA", category: "emociones", sourceUrl: mineduc },
  { id: "mps-cuerpo", title: "Cuerpo humano — Mis Primeras Señas, capítulo 19", author: "Lóbulo Temporal · difundido por Mineduc", url: "https://www.youtube.com/watch?v=7Flx1lIjTIo", category: "cuerpo", sourceUrl: mineduc },
];
