-- Run in one transaction with deafapp.test_password set locally by the operator.
-- The two synthetic records and their decisions are rolled back; no recording file is uploaded.
begin;
set local role anon;
do $$
declare v_login jsonb; v_token text; v_first bigint; v_second bigint; v_result jsonb; v_denied boolean;
begin
  v_login := public.deafapp_admin_login('incorrecta-para-verificacion');
  assert v_login->>'code'='invalid_password', 'Wrong password accepted';
  v_login := public.deafapp_admin_login(current_setting('deafapp.test_password',true));
  assert (v_login->>'ok')::boolean, 'Login failed'; v_token := v_login->>'token';
  v_denied := false;
  begin perform public.deafapp_admin_list(repeat('0',64),'all','',0,25);
    exception when sqlstate '28000' then v_denied := true; end;
  assert v_denied, 'Anonymous listing accepted';
  v_denied := false;
  begin perform singleton from deafapp_private.admin_config;
    exception when insufficient_privilege then v_denied := true; end;
  assert v_denied, 'Private configuration exposed';
  v_denied := false;
  begin insert into public.grabaciones(label,categoria,archivo_path,aprobada) values ('verificacion-admin','prueba_admin','__admin_test__/invalid.json',true);
    exception when insufficient_privilege then v_denied := true; end;
  assert v_denied, 'Contributor can insert approval';
  insert into public.grabaciones(label,categoria,archivo_path) values ('verificacion-admin-uno','prueba_admin','__admin_test__/one.json') returning id into v_first;
  insert into public.grabaciones(label,categoria,archivo_path) values ('verificacion-admin-dos','prueba_admin','__admin_test__/two.json') returning id into v_second;
  assert exists(select 1 from public.grabaciones where id=v_first and moderation_status='pending' and not aprobada), 'New contribution is not pending';
  v_denied := false;
  begin update public.grabaciones set aprobada=true where id=v_first;
    exception when insufficient_privilege then v_denied := true; end;
  assert v_denied, 'Contributor can update approval';
  v_result := public.deafapp_admin_review(v_token,jsonb_build_array(jsonb_build_object('id',v_first::text,'version',0)),'approved');
  assert (v_result->>'changed')::integer=1, 'Approval did not apply';
  assert exists(select 1 from public.grabaciones where id=v_first and aprobada and visible and validada and moderation_version=1), 'Approval is inconsistent';
  v_denied := false;
  begin perform public.deafapp_admin_review(v_token,jsonb_build_array(jsonb_build_object('id',v_first::text,'version',0)),'rejected');
    exception when sqlstate '40001' then v_denied := true; end;
  assert v_denied, 'Stale decision overwrote a review';
  assert exists(select 1 from public.grabaciones where id=v_first and aprobada), 'Failed review changed approval';
  perform public.deafapp_admin_review(v_token,jsonb_build_array(jsonb_build_object('id',v_first::text,'version',1)),'rejected');
  assert exists(select 1 from public.grabaciones where id=v_first and not aprobada and not visible and moderation_status='rejected'), 'Rejection did not persist';
  perform public.deafapp_admin_review(v_token,jsonb_build_array(jsonb_build_object('id',v_first::text,'version',2)),'pending');
  v_result := public.deafapp_admin_review(v_token,jsonb_build_array(jsonb_build_object('id',v_first::text,'version',3),jsonb_build_object('id',v_second::text,'version',0)),'approved');
  assert (v_result->>'changed')::integer=2, 'Batch did not apply';
  v_denied := false;
  begin perform public.deafapp_admin_review(v_token,jsonb_build_array(jsonb_build_object('id',v_first::text,'version',4),jsonb_build_object('id',v_second::text,'version',0)),'rejected');
    exception when sqlstate '40001' then v_denied := true; end;
  assert v_denied, 'Stale batch was accepted';
  assert (select count(*) from public.grabaciones where id in(v_first,v_second) and aprobada)=2, 'Batch failed partially';
  v_result := public.deafapp_admin_list(v_token,'all','verificacion-admin',0,25);
  assert (v_result->>'total')::integer=2, 'Search/list is incomplete';
  perform public.deafapp_admin_overview(v_token);
  perform public.deafapp_admin_logout(v_token);
  v_denied := false;
  begin perform public.deafapp_admin_list(v_token,'all','',0,25);
    exception when sqlstate '28000' then v_denied := true; end;
  assert v_denied, 'Logout failed to revoke the session';
end $$;
rollback;
select true as checks_passed, 'auth, privileges, contribution, approve/reject, concurrency, batch atomicity, logout; test records rolled back' as verification;
